# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Hello world!'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'cloudstorage-TFSPN'
    backendAzureRmResourceGroupName: 'cloud-shell-storage-northeurope'
    backendAzureRmStorageAccountName: 'epam0lectures'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'
  displayName: 'Terraform : Init'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'validate'
  displayName: 'Terraform : Validate'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'cloudstorage-TFSPN'
  displayName: 'Terraform : Plan'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'cloudstorage-TFSPN'
  displayName: 'Terraform : Apply'



